; PlatformIO Project Configuration File
; Build all node types: pio run -e sender -e intermediate -e receiver

[platformio]
default_envs = sender, intermediate, receiver

[env:base]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 9600
lib_deps =
  painlessMesh
  bblanchon/ArduinoJson@^6.21.0

[env:sender]
extends = env:base
src_dir = firmware/sender-node
board_build.filesystem = littlefs

[env:intermediate]
extends = env:base
src_dir = firmware/intermediate-node

[env:receiver]
extends = env:base
src_dir = firmware/receiver-node
